#!/bin/bash
#  
# licensed	netbrain license agent server
#
# chkconfig: 2345 10 90
# description:  This shell script takes care of starting and stopping proxyserver  
# 		created on Sep. 24th, 2017  
#  
# Source function library  

. /etc/init.d/functions

#the service name  for example: dennis
SNAME=licensed
LICENSE_USER=netbrain
LICENSE_GROUP=netbrain

#the full path and name of the daemon program  
#Warning: The name of executable file must be identical with service name  
PROG=/bin/netbrainlicense/$SNAME


# start function  
start() {
    #use the same ulimit setting with mogodb
    ulimit -f unlimited
    ulimit -t unlimited
    ulimit -v unlimited
    ulimit -n 64000
    ulimit -m unlimited
    ulimit -u 64000
    ulimit -c unlimited
    
    #check the daemon status first  
    if [ -f /var/lock/subsys/$SNAME ]
    then
        echo "$SNAME is already started!"  
        exit 0;
    else
        action "Starting $SNAME ..." $PROG
        #echo "Starting $SNAME ..."
        #daemon --user "$LICENSE_USER" --check $SNAME $PROG >/dev/null 2>&1
        #daemon --user "$LICENSE_USER" $PROG >/dev/null 2>&1
        #echo $?
        [ $? -eq 0 ] && touch /var/lock/subsys/$SNAME
        exit 0;
    fi
}

#stop function  
stop() {
    echo "Stopping $SNAME ..."  
    killproc $SNAME
    rm -rf /var/lock/subsys/$SNAME

}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
reload|restart)
  stop
  start
  ;;
status)
  status $SNAME
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status}"  
  exit 1
esac

